- name: Visual Studio Code
  block:
    - name: Install Visual Studio Code
      homebrew_cask:
        name: visual-studio-code
        state: present
        install_options: 'appdir=/Applications/Development'

    - name: List Installed Plugins
      command: code --list-extensions
      register: installed_extensions
      check_mode: no
      changed_when: false

    - name: Install Plugins
      command: "code --install-extension {{ item.id | default(item) }}"
      with_items: "{{ VISUAL_STUDIO_CODE_EXTENSIONS }}"
      when: item.id | default(item) not in installed_extensions.stdout
      loop_control:
        label: "{{ item.name | default(item) }}"

    - name: Make Visual Studio Code Default Git Editor
      git_config:
        name: core.editor
        scope: global
        value: "code --wait"

  when: VISUAL_STUDIO_CODE_INSTALL == true
